In [1]:
# example of loss calculation:
import torch
# say our prediction length is 5:
pred =   torch.tensor([1.0, 1.0, 3.0, 2.3, 4.1])   # predictions of model in training process
target = torch.tensor([2.2, 1.0, 1.0, 2.5,  3.0])   # ground truth
print("pred:                                      ", pred)
print("target:                                    ", target)
print()
print("Error=abs(pred-target):                    ", torch.abs(pred - target))
mse_loss = torch.mean((pred - target) ** 2)
print()
print(f"'Regular' MSE between pred and target:      {mse_loss.item():.3f}")
print()
Pt = 1                                              # penalty threshold
Pf = 1.2                                            # penalty factor
print("Penalty threshold - Pt:                    ", Pt)
print("Penalty factor - Pf:                       ", Pf)
print()
print("For each cell in error vector we check if abs(pred-target)>Pt and we create a mask vector:\n")
mask = (torch.abs(pred - target) > Pt).float()  # this is a vector that determines if we multiply with Pf
print("mask:                                      ", mask,"\n")

# mse_loss_penalized = mse_loss * ( 1 + mask * (Pf - 1) )            
# mse_loss_penalized = mse_loss_penalized.mean()
print(mask * (Pf - 1))
print(1+mask * (Pf - 1))
print(mse_loss * (1 + mask * (Pf - 1)))
print( (mse_loss * (1 + mask * (Pf - 1))).mean())
# mask * (Pf - 1)

pred:                                       tensor([1.0000, 1.0000, 3.0000, 2.3000, 4.1000])
target:                                     tensor([2.2000, 1.0000, 1.0000, 2.5000, 3.0000])

Error=abs(pred-target):                     tensor([1.2000, 0.0000, 2.0000, 0.2000, 1.1000])

'Regular' MSE between pred and target:      1.338

Penalty threshold - Pt:                     1
Penalty factor - Pf:                        1.2

For each cell in error vector we check if abs(pred-target)>Pt and we create a mask vector:

mask:                                       tensor([1., 0., 1., 0., 1.]) 

tensor([0.2000, 0.0000, 0.2000, 0.0000, 0.2000])
tensor([1.2000, 1.0000, 1.2000, 1.0000, 1.2000])
tensor([1.6056, 1.3380, 1.6056, 1.3380, 1.6056])
tensor(1.4986)
